Hide ImageTextAlternative balloon when image element has been removed
ckeditor/ckeditor5-image pull request #138
Opened 2017-09-08 18:12 UTC by oskarwrobel

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Hide `ImageTextAlternative` balloon when image element has been removed by external changes. Closes #137.

2017-09-11 11:13 UTC, oleq commented
Shouldn't this issue be included in http://localhost:8125/ckeditor5-ui/tests/manual/contextualballoon/externalchanges.html or provide a new MT?

2017-09-11 11:13 UTC, oleq requested changes
Minor changes needed in tests.

2017-09-11 11:13 UTC, oleq commented on tests/image/utils.js
> +			frag = new ViewDocumentFragment( [ notWidgetizedElement, notWidgetizedElement ] );
Shouldn't this be `new ViewDocumentFragment( [ element, notWidgetizedElement ] )` instead?

2017-09-11 14:58 UTC, oskarwrobel commented
> Shouldn't this issue be included in http://localhost:8125/ckeditor5-ui/tests/manual/contextualballoon/externalchanges.html or provide a new MT?

I was thinking about it but this is something that we are able to test by our unit tests. I think MT is useful to test repositioning because this is something we need to stub in unit tests.

But I can add MT if you think is needed for this case.

2017-09-12 08:40 UTC, oleq commented
For one thing, I was surprised that the MT is in ckeditor5-ui instead of ckeditor5-link. The code which handles re-positioning and stuff on `#render` isn't in the `ContextualBalloon`. It's a pure link stuff. 

Then I thought that we should check the same thing in the image and I finally found out there's a corresponding test in the image too ckeditor5-image/tests/manual/tickets/106/1.html. It doesn't test this kind of issue because what is "remotely" removed is the paragraph before the image instead of the image widget itself.

So maybe, let's just extend this MT and include this issue's case?

2017-09-12 08:45 UTC, oskarwrobel commented
I was using `106` MT to prepare the GIF for this issue. OK, I'll extend this test.

2017-09-12 09:59 UTC, oleq commented
The MT is OK. But it revealed that the editor loses focus when the image which text alternative is being edited gets removed. This, I'm afraid, must be addressed (it works in the link feature).

2017-09-13 07:55 UTC, merged