Enable image in table cells.
ckeditor/ckeditor5-image pull request #262
Opened 2018-12-13 10:17 UTC by jodator

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Enable image in table cells.

---

### Additional information

* Part of: https://github.com/ckeditor/ckeditor5-table/pull/155

2018-12-19 00:01 UTC, J-Nagle commented
Thanks very much for responding to our feedback in https://github.com/ckeditor/ckeditor5-table/pull/155#issuecomment-446797016. However, this gave us a `TypeError` when we went to test it. Attached is our build, below is the error, and here are links to the [configuration](https://pastebin.com/6WvB13au) and [stack trace](https://pastebin.com/xaJq9xLn). Hopefully this is enough...

```
TypeError: t.plugins.has is not a function
	at af.init (imageuploadediting.js:94)
InlineEditor.create.then.catch.error @ app.js:335 // When our system calls CKEditor
```
[CKEditor - Table image upload test build.zip](https://github.com/ckeditor/ckeditor5-image/files/2692701/CKEditor.-.Table.image.upload.test.build.zip)

2018-12-19 00:16 UTC, jodator commented
@J-Nagle looks like latest changes in master :) I've updated PR branches on
- ckeditor/ckeditor5-engine
- ckeditor/ckeditor5-widget

It should be OK but I'll test it better tomorrow morning as now I'm not able to properly test it.

Also I'll try to push work on this PR faster but nevertheless those changes will be publicly available in next release. Now it may fail as `master` branch is considered a working branch.

2018-12-19 00:54 UTC, J-Nagle commented
Thanks for the fast response! The updated masters of Engine and Widget still don't make this work for us right now, but I absolutely appreciate the quick tweak nonetheless. Of course, we understand that other work may take priority, and will definitely upgrade to the next release when available. Cheers!

2018-12-19 16:57 UTC, scofalik requested changes
Small things.

2018-12-19 16:57 UTC, scofalik commented on src/image/utils.js
> +	return !( !!selectedElement && schema.isObject( selectedElement ) );
Doesn't this return the opposite thing? If this is checking if the selection is on object it should simply return:

`return selectedElement && schema.isObject( selectedElement );`

2018-12-19 16:57 UTC, scofalik commented on src/image/utils.js
> +	return [ ...selection.focus.getAncestors() ].every( ancestor => !ancestor.is( 'image' ) );
Simple optimization would be to check `.some` xD.

2018-12-20 09:39 UTC, jodator commented on src/image/utils.js
> +	return [ ...selection.focus.getAncestors() ].every( ancestor => !ancestor.is( 'image' ) );
How would it be better then `.every`?

Both will return if condition is other then expected:
```js
.some( a => a.is( 'image' ) );
.every( a => !a.is( 'image' ) );
```

2018-12-20 09:51 UTC, merged