The image uploading listener for handling `base64/blob` images no longer stops `inputTransformation` event
ckeditor/ckeditor5-image pull request #264
Opened 2018-12-17 15:04 UTC by f1ames

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: The image uploading listener for handling `base64/blob` images no longer stops `inputTransformation` event. Closes #263.

---

### Additional information

This PR aligns the way `base64/blob` images uploading works to https://github.com/ckeditor/ckeditor5-upload/issues/87 issue in which the `FileLoader` accepts `Promise` instead of `File` instance.

It's nice to see how much `inputTransformation` listener got simplified. However, tests got a little more complex.

_This PR is based on #258 PR and will not work without https://github.com/ckeditor/ckeditor5-upload/issues/87 so should be closed after closing this mentioned PRs. The CI will be red unless https://github.com/ckeditor/ckeditor5-upload/issues/87 is merged._

2019-01-11 15:43 UTC, jodator commented
@f1ames I've forgot about this one after checking the images upload. It is still valid right?
If so could you check conflicts with master? I'll review it first thing next business day :)

2019-01-14 10:26 UTC, f1ames commented
Still failing on Edge, due to some reason 🤔 I will look into it.

2019-01-14 14:18 UTC, jodator commented on src/imageupload/imageuploadediting.js
> +				const writer = new UpcastWriter();
Hmm I'm worried about that construct. I think that we could expose those methods on the view if they're need. Then we could write it as:

```js
const view = editor.editing.view; // ps.: also used for crateRangeIn()

/// the code as now

view.setAttribute( 'src', '', fetchableImage.imageElement );
```
This unfortunately will require small changes in the engine.

2019-01-14 14:29 UTC, jodator requested changes
Cosmetics to change really.

2019-01-14 14:29 UTC, jodator commented on src/imageupload/imageuploadediting.js
> +				const writer = new UpcastWriter();
Hmm I'm worried about that construct. I think that we could expose those methods on the view if they're need. Tahen we could write it as:

```js
const view = editor.editing.view; // ps.: also used for crateRangeIn()

/// the code as now

view.setAttribute( 'src', '', fetchableImage.imageElement );
```
This unfortunately will require small changes in the engine.

Edit: I've just found this construct in the Clipboard docs. I'll report an issue there. So do not change this ATM.

2019-01-14 14:29 UTC, jodator commented on src/imageupload/utils.js
>   * @returns {Promise} A promise which resolves when image source is fetched and converted to `File` instance.
```suggestion
 * @returns {Promise.<File>} A promise which resolves when image source is fetched and converted to `File` instance.
```

2019-01-14 14:29 UTC, jodator commented on src/imageupload/utils.js
>  			.catch( () => {
Meybe leave it as `.catch( reject )`? WDYT will be shorter.

2019-01-14 14:37 UTC, jodator commented on src/imageupload/imageuploadediting.js
> +				const writer = new UpcastWriter();
ps.: reporter here: https://github.com/ckeditor/ckeditor5-clipboard/issues/46#issuecomment-454025196

2019-01-14 14:46 UTC, jodator commented
As the code is ready: @Mgsy could you check this one?

2019-01-15 15:17 UTC, f1ames commented on src/imageupload/imageuploadediting.js
> +				const writer = new UpcastWriter();
Ok, I'll leave it as is for now. Btw. one may use `change` block here:

```js
editor.editing.view.change( writer => {
    // code...
} );
```

to obtain the `writer`. However, it uses `DowncastWriter` not `UpcastWriter` (still their `setAttribute()` methods uses exactly same API).

2019-01-15 15:21 UTC, jodator commented on src/imageupload/imageuploadediting.js
> +				const writer = new UpcastWriter();
I was thinking abut it and while it looks safe we probably ought to fix it globally as in referenced ticket.

2019-01-16 09:19 UTC, Mgsy commented
I'm not able to paste an image from Word to the editor (other browsers work fine). Tested on VM.

![bug_cke5](https://user-images.githubusercontent.com/20988892/51238772-04def000-1978-11e9-85b2-f11f38ba0f23.gif)

2019-01-16 10:13 UTC, f1ames commented
> I'm not able to paste an image from Word to the editor in Edge (other browsers work fine and the sample has PFO plugin activated). Tested on VM.

That's probably caused by the lack of support for `File` constructor in Edge. However, in this case the image should be pasted (as blob) and no error should be shown (I guess it is not handled correctly ATM).

2019-01-16 10:47 UTC, jodator commented
> That's probably caused by the lack of support for `File` constructor in Edge. However, in this case the image should be pasted (as blob) and no error should be shown (I guess it is not handled correctly ATM).

So should this be fixed here or in PFO plugin?

2019-01-16 12:52 UTC, f1ames commented
☝️ Sorry, didn't make it clear in the previous comment. It should be fixed in this PR from what I can see and I'm working on the fix ATM.

2019-01-16 13:25 UTC, f1ames commented
> However, in this case the image should be pasted (as blob) and no error should be shown (I guess it is not handled correctly ATM).

Mixed up a little bit, we cannot use blob here due to collaboration features (it may break it). So the image simply will not be pasted. However, `undefined` alert is unnecessary. I think we should skip any messages here.

2019-01-16 14:26 UTC, f1ames commented
Funny that there is no error in Edge in the case @Mgsy found. In Chrome (when file promise is rejected) there is - so I have added a fix there too - https://github.com/ckeditor/ckeditor5-upload/pull/90. Please review and merge it together with this PR.

2019-01-16 15:02 UTC, Mgsy commented
>I have added a fix there too - ckeditor/ckeditor5-upload#90. Please review and merge it together with this PR.

After switching to this branch, indeed, the image isn't pasted in Edge, but unfortunately, the `undefined` alert is still displayed.

2019-01-16 15:21 UTC, f1ames commented
@Mgsy I have pushed a fix. In Edge image should not be pasted, no errors in the console and no alert displayed.

2019-01-16 15:33 UTC, Mgsy approved these changes
👌

2019-01-22 14:36 UTC, jodator approved these changes

2019-01-22 14:36 UTC, merged